[package]
name = "lox"
version = "0.1.0"
authors = ["Mayank Tripathi <ryotsu@kochika.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
name = "lox"
path = "src/lib/mod.rs"

[dependencies]
itertools = "0.7.8"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "z"
lto = true
